export const GET_CONTACTS = "GET_CONTACTS"
export const EDIT_RECORD = "EDIT_RECORD"
export const UPLOAD_RECORD = "UPLOAD_RECORD"
export const STATE_MODAL = "STATE_MODAL"
export const LOGIN_USER = "LOGIN_USER"